// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmeBackend.Data;

#nullable disable

namespace SmeBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260809120919_AddUserRole")]
    partial class AddUserRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmeBackend.Models.AgentWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("InputPayload")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutputPayload")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TenantId");

                    b.ToTable("AgentWorkflows");
                });

            modelBuilder.Entity("SmeBackend.Models.AvailabilitySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "StartTime", "EndTime");

                    b.ToTable("AvailabilitySlots");
                });

            modelBuilder.Entity("SmeBackend.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AgentWorkflowId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentWorkflowId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ResourceId", "StartTime", "EndTime");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SmeBackend.Models.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Address = "123 Galle Road, Colombo 3",
                            CreatedAt = new DateTime(2026, 8, 9, 12, 9, 16, 230, DateTimeKind.Utc).AddTicks(2310),
                            IsActive = true,
                            Name = "Colombo Main Branch",
                            Phone = "+94112345678",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 8, 9, 12, 9, 16, 230, DateTimeKind.Utc).AddTicks(2310)
                        });
                });

            modelBuilder.Entity("SmeBackend.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SmeBackend.Models.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResourceType")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("BranchId", "Name")
                        .IsUnique();

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("SmeBackend.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BusinessType = "",
                            CreatedAt = new DateTime(2026, 8, 9, 12, 9, 16, 229, DateTimeKind.Utc).AddTicks(8986),
                            IsActive = true,
                            Name = "Lumenis",
                            UpdatedAt = new DateTime(2026, 8, 9, 12, 9, 16, 229, DateTimeKind.Utc).AddTicks(8986)
                        });
                });

            modelBuilder.Entity("SmeBackend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BranchId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 8, 9, 12, 9, 16, 372, DateTimeKind.Utc).AddTicks(5104),
                            Email = "admin@lumenis.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$EIaLI3.KF/2qGiN87F1w1.qNByWPZBBC1m6gbl5gybsBe8cMXOAUq",
                            Phone = "+94123456789",
                            Role = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 8, 9, 12, 9, 16, 372, DateTimeKind.Utc).AddTicks(5109)
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            BranchId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 8, 9, 12, 9, 16, 599, DateTimeKind.Utc).AddTicks(9511),
                            Email = "manager@lumenis.com",
                            FullName = "Branch Manager",
                            IsActive = true,
                            PasswordHash = "$2a$11$BNeA3Oc2s8qQOIbU1sGsAuduc7d2qTUUswYWD5UGcBgbmZOeyXQ5i",
                            Phone = "+94123456780",
                            Role = 1,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 8, 9, 12, 9, 16, 599, DateTimeKind.Utc).AddTicks(9516)
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            BranchId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 8, 9, 12, 9, 16, 778, DateTimeKind.Utc).AddTicks(3203),
                            Email = "staff@lumenis.com",
                            FullName = "Staff Member",
                            IsActive = true,
                            PasswordHash = "$2a$11$v4DzEetQJUG7Sx8qpX3H9ejRREXahGL/Hyy9MN98KsQhEiA9nqnLu",
                            Phone = "+94123456781",
                            Role = 2,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 8, 9, 12, 9, 16, 778, DateTimeKind.Utc).AddTicks(3208)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2026, 8, 9, 12, 9, 16, 960, DateTimeKind.Utc).AddTicks(832),
                            Email = "customer@lumenis.com",
                            FullName = "Test Customer",
                            IsActive = true,
                            PasswordHash = "$2a$11$rMhm0Fg7WRPNSFGsD3M1XObBbH.SwwKiSo6xFyuNvXsXlnT./zaA6",
                            Phone = "+94123456782",
                            Role = 3,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 8, 9, 12, 9, 16, 960, DateTimeKind.Utc).AddTicks(837)
                        });
                });

            modelBuilder.Entity("SmeBackend.Models.AgentWorkflow", b =>
                {
                    b.HasOne("SmeBackend.Models.Branch", "Branch")
                        .WithMany("AgentWorkflows")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmeBackend.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmeBackend.Models.Tenant", "Tenant")
                        .WithMany("AgentWorkflows")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SmeBackend.Models.AvailabilitySlot", b =>
                {
                    b.HasOne("SmeBackend.Models.Resource", "Resource")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("SmeBackend.Models.Booking", b =>
                {
                    b.HasOne("SmeBackend.Models.AgentWorkflow", "AgentWorkflow")
                        .WithMany()
                        .HasForeignKey("AgentWorkflowId");

                    b.HasOne("SmeBackend.Models.Branch", "Branch")
                        .WithMany("Bookings")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmeBackend.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmeBackend.Models.User", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmeBackend.Models.Resource", "Resource")
                        .WithMany("Bookings")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmeBackend.Models.Tenant", "Tenant")
                        .WithMany("Bookings")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentWorkflow");

                    b.Navigation("Branch");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("Resource");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SmeBackend.Models.Branch", b =>
                {
                    b.HasOne("SmeBackend.Models.Tenant", "Tenant")
                        .WithMany("Branches")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SmeBackend.Models.RefreshToken", b =>
                {
                    b.HasOne("SmeBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmeBackend.Models.Resource", b =>
                {
                    b.HasOne("SmeBackend.Models.Branch", "Branch")
                        .WithMany("Resources")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmeBackend.Models.Tenant", "Tenant")
                        .WithMany("Resources")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SmeBackend.Models.User", b =>
                {
                    b.HasOne("SmeBackend.Models.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmeBackend.Models.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SmeBackend.Models.Branch", b =>
                {
                    b.Navigation("AgentWorkflows");

                    b.Navigation("Bookings");

                    b.Navigation("Resources");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmeBackend.Models.Resource", b =>
                {
                    b.Navigation("AvailabilitySlots");

                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("SmeBackend.Models.Tenant", b =>
                {
                    b.Navigation("AgentWorkflows");

                    b.Navigation("Bookings");

                    b.Navigation("Branches");

                    b.Navigation("Resources");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmeBackend.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
