import 'package:flutter/material.dart';

import 'auth/app_role.dart';
import 'auth/auth_controller.dart';
import 'auth/auth_repository.dart';
import 'auth/auth_session.dart';

const apiBaseUrl = String.fromEnvironment('API_BASE_URL', defaultValue: 'http://10.0.2.2:5107');
const navy = Color(0xFF243B78), mint = Color(0xFF16A394), canvas = Color(0xFFF6F8FC);

void main() { WidgetsFlutterBinding.ensureInitialized(); final auth = AuthController(AuthRepository(apiBaseUrl: apiBaseUrl)); runApp(App(auth: auth)); auth.restore(); }

class App extends StatelessWidget {
  const App({super.key, required this.auth}); final AuthController auth;
  @override Widget build(BuildContext context) => MaterialApp(debugShowCheckedModeBanner: false, title: 'SME Inventory', theme: ThemeData(useMaterial3: true, colorScheme: ColorScheme.fromSeed(seedColor: navy), scaffoldBackgroundColor: canvas, inputDecorationTheme: InputDecorationTheme(filled: true, fillColor: const Color(0xFFF9FAFB), border: border(), enabledBorder: border(), focusedBorder: border(navy, 2)), filledButtonTheme: FilledButtonThemeData(style: FilledButton.styleFrom(backgroundColor: navy, minimumSize: const Size.fromHeight(54), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14))))), home: AnimatedBuilder(animation: auth, builder: (_, __) => auth.isRestoring ? const Scaffold(body: Center(child: CircularProgressIndicator())) : AnimatedSwitcher(duration: const Duration(milliseconds: 350), child: auth.session == null ? Login(key: const ValueKey('login'), auth: auth) : Shell(key: const ValueKey('shell'), auth: auth, session: auth.session!))));
}
OutlineInputBorder border([Color color = const Color(0xFFE2E8F0), double width = 1]) => OutlineInputBorder(borderRadius: BorderRadius.circular(14), borderSide: BorderSide(color: color, width: width));

class LoginScreen extends StatefulWidget { const LoginScreen({super.key, required this.auth}); final AuthController auth; @override State<LoginScreen> createState() => _LoginState(); }
class Login extends LoginScreen { const Login({super.key, required super.auth}); }
class _LoginState extends State<LoginScreen> {
  final form = GlobalKey<FormState>(); final email = TextEditingController(), password = TextEditingController(); bool busy = false, hidden = true; String? error;
  @override void dispose() { email.dispose(); password.dispose(); super.dispose(); }
  Future<void> submit() async { if (!form.currentState!.validate()) return; setState(() { busy = true; error = null; }); try { await widget.auth.login(email.text.trim(), password.text); } on AuthException catch (e) { if (mounted) setState(() => error = e.message); } catch (_) { if (mounted) setState(() => error = 'Unable to reach the server.'); } finally { if (mounted) setState(() => busy = false); } }
  @override Widget build(BuildContext context) => Scaffold(body: Stack(children: [const Backdrop(), Center(child: SingleChildScrollView(padding: const EdgeInsets.all(24), child: TweenAnimationBuilder<double>(tween: Tween(begin: 0, end: 1), duration: const Duration(milliseconds: 600), curve: Curves.easeOutCubic, builder: (_, value, child) => Opacity(opacity: value, child: Transform.translate(offset: Offset(0, 24 * (1 - value)), child: child)), child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 440), child: Card(elevation: 0, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(28), side: const BorderSide(color: Color(0xFFE5EAF2))), child: Padding(padding: const EdgeInsets.all(32), child: Form(key: form, child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [const Logo(), const SizedBox(height: 28), Text('Welcome back', style: Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight: FontWeight.w800)), const SizedBox(height: 8), const Text('Sign in to manage your inventory with ease.', style: TextStyle(color: Color(0xFF667085))), const SizedBox(height: 28), TextFormField(controller: email, keyboardType: TextInputType.emailAddress, decoration: const InputDecoration(labelText: 'Email address', prefixIcon: Icon(Icons.mail_outline_rounded)), validator: (v) => v == null || v.trim().isEmpty ? 'Email is required' : null), const SizedBox(height: 16), TextFormField(controller: password, obscureText: hidden, onFieldSubmitted: (_) => submit(), decoration: InputDecoration(labelText: 'Password', prefixIcon: const Icon(Icons.lock_outline_rounded), suffixIcon: IconButton(onPressed: () => setState(() => hidden = !hidden), icon: Icon(hidden ? Icons.visibility_outlined : Icons.visibility_off_outlined))), validator: (v) => v == null || v.isEmpty ? 'Password is required' : null), if (error != null) Padding(padding: const EdgeInsets.only(top: 16), child: ErrorBox(error!)), const SizedBox(height: 24), FilledButton.icon(onPressed: busy ? null : submit, icon: busy ? const SizedBox(height: 18, width: 18, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white)) : const Icon(Icons.arrow_forward_rounded), label: Text(busy ? 'Signing in...' : 'Sign in')), const SizedBox(height: 20), const Row(children: [Icon(Icons.shield_outlined, color: mint, size: 17), SizedBox(width: 8), Text('Your session is secured and encrypted.', style: TextStyle(fontSize: 12, color: Color(0xFF667085)))])]))))))))]));
}
class Backdrop extends StatelessWidget { const Backdrop({super.key}); @override Widget build(BuildContext c) => Stack(children: [Container(color: canvas), Positioned(top: -150, left: -100, child: glow(330, navy.withValues(alpha: .12))), Positioned(bottom: -180, right: -90, child: glow(360, mint.withValues(alpha: .12)))]); Widget glow(double size, Color color) => Container(width: size, height: size, decoration: BoxDecoration(shape: BoxShape.circle, color: color)); }
class Logo extends StatelessWidget { const Logo({super.key}); @override Widget build(BuildContext c) => Row(children: [Container(padding: const EdgeInsets.all(11), decoration: BoxDecoration(color: navy, borderRadius: BorderRadius.circular(14)), child: const Icon(Icons.inventory_2_rounded, color: Colors.white)), const SizedBox(width: 12), const Text('SME Inventory', style: TextStyle(fontWeight: FontWeight.w800, fontSize: 18))]); }
class ErrorBox extends StatelessWidget { const ErrorBox(this.message, {super.key}); final String message; @override Widget build(BuildContext c) => Container(padding: const EdgeInsets.all(12), decoration: BoxDecoration(color: const Color(0xFFFFF1F0), borderRadius: BorderRadius.circular(12)), child: Row(children: [const Icon(Icons.error_outline, color: Color(0xFFB42318)), const SizedBox(width: 10), Expanded(child: Text(message, style: const TextStyle(color: Color(0xFFB42318))) )])); }

class Shell extends StatefulWidget { const Shell({super.key, required this.auth, required this.session}); final AuthController auth; final AuthSession session; @override State<Shell> createState() => _ShellState(); }
class _ShellState extends State<Shell> { int index = 0; @override Widget build(BuildContext context) { final analytics = widget.session.hasAnyRole([AppRole.admin, AppRole.manager]); final pages = [const Inventory(), if (analytics) const Analytics()]; final destinations = [const NavigationDestination(icon: Icon(Icons.inventory_2_outlined), selectedIcon: Icon(Icons.inventory_2), label: 'Inventory'), if (analytics) const NavigationDestination(icon: Icon(Icons.insights_outlined), selectedIcon: Icon(Icons.insights), label: 'Analytics')]; final current = index >= pages.length ? 0 : index; return Scaffold(appBar: AppBar(toolbarHeight: 78, title: const Logo(), actions: [Padding(padding: const EdgeInsets.only(right: 16), child: IconButton.filledTonal(onPressed: widget.auth.logout, tooltip: 'Sign out', icon: const Icon(Icons.logout_rounded))) ]), body: AnimatedSwitcher(duration: const Duration(milliseconds: 240), child: KeyedSubtree(key: ValueKey(current), child: pages[current])), bottomNavigationBar: NavigationBar(selectedIndex: current, onDestinationSelected: (v) => setState(() => index = v), destinations: destinations)); }}
class Inventory extends StatelessWidget { const Inventory({super.key}); @override Widget build(BuildContext c) => PageFrame(title: 'Inventory at a glance', subtitle: 'A clear view of stock health and what needs attention today.', action: FilledButton.icon(onPressed: () {}, icon: const Icon(Icons.add_rounded), label: const Text('Add item')), children: [LayoutBuilder(builder: (_, b) { final count = b.maxWidth > 900 ? 4 : b.maxWidth > 600 ? 2 : 1; return GridView.count(crossAxisCount: count, childAspectRatio: count == 1 ? 2.5 : 1.55, shrinkWrap: true, physics: const NeverScrollableScrollPhysics(), crossAxisSpacing: 16, mainAxisSpacing: 16, children: const [Metric('Total items', '248', '12 added this month', Icons.inventory_2_outlined, navy), Metric('In stock', '1,842', 'Units available', Icons.check_circle_outline, mint), Metric('Low stock', '18', 'Needs attention', Icons.warning_amber_rounded, Color(0xFFD97706)), Metric('Suppliers', '24', 'Active partners', Icons.local_shipping_outlined, Color(0xFF7C3AED))]); }), const SizedBox(height: 28), const Heading('Quick actions', 'Keep your daily stock work moving.'), const SizedBox(height: 14), Wrap(spacing: 12, runSpacing: 12, children: const [ActionTile(Icons.add_box_outlined, 'New item', navy), ActionTile(Icons.swap_horiz_rounded, 'Stock adjustment', mint), ActionTile(Icons.shopping_cart_outlined, 'Purchase order', Color(0xFF7C3AED)), ActionTile(Icons.group_outlined, 'Suppliers', Color(0xFFD97706))]), const SizedBox(height: 28), const Heading('Stock alerts', 'Items that may need reordering soon.'), const SizedBox(height: 14), const Alerts()]); }
class Analytics extends StatelessWidget { const Analytics({super.key}); @override Widget build(BuildContext c) => PageFrame(title: 'Inventory intelligence', subtitle: 'Use these signals to make confident stocking decisions.', action: OutlinedButton.icon(onPressed: () {}, icon: const Icon(Icons.download_outlined), label: const Text('Export report')), children: const [Wrap(spacing: 16, runSpacing: 16, children: [Metric('Stock turnover', '6.8x', '+8.2% vs last month', Icons.trending_up_rounded, mint), Metric('Inventory value', 'LKR 42.8k', 'Across 248 products', Icons.savings_outlined, navy), Metric('Days of stock', '31', 'Healthy coverage', Icons.timer_outlined, Color(0xFF7C3AED))]), SizedBox(height: 28), ChartCard()]); }
class PageFrame extends StatelessWidget { const PageFrame({super.key, required this.title, required this.subtitle, required this.action, required this.children}); final String title, subtitle; final Widget action; final List<Widget> children; @override Widget build(BuildContext c) => LayoutBuilder(builder: (_, b) => SingleChildScrollView(padding: EdgeInsets.fromLTRB(b.maxWidth > 700 ? 40 : 20, 12, b.maxWidth > 700 ? 40 : 20, 36), child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 1180), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Wrap(spacing: 20, runSpacing: 14, crossAxisAlignment: WrapCrossAlignment.center, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('OPERATIONS', style: TextStyle(color: mint, fontSize: 12, fontWeight: FontWeight.w800, letterSpacing: 1.2)), const SizedBox(height: 6), Text(title, style: Theme.of(c).textTheme.headlineMedium?.copyWith(fontWeight: FontWeight.w800)), const SizedBox(height: 6), Text(subtitle, style: const TextStyle(color: Color(0xFF667085)))]), action]), const SizedBox(height: 28), ...children]))))); }
class Metric extends StatelessWidget { const Metric(this.label, this.value, this.note, this.icon, this.color, {super.key}); final String label, value, note; final IconData icon; final Color color; @override Widget build(BuildContext c) => Card(elevation: 0, color: Colors.white, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20), side: const BorderSide(color: Color(0xFFE7ECF3))), child: Padding(padding: const EdgeInsets.all(20), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(padding: const EdgeInsets.all(9), decoration: BoxDecoration(color: color.withValues(alpha: .11), borderRadius: BorderRadius.circular(11)), child: Icon(icon, color: color)), const Spacer(), Text(value, style: const TextStyle(fontSize: 28, fontWeight: FontWeight.w800)), Text(label, style: const TextStyle(fontWeight: FontWeight.w700)), Text(note, style: const TextStyle(fontSize: 12, color: Color(0xFF667085)))]))); }
class Heading extends StatelessWidget { const Heading(this.title, this.detail, {super.key}); final String title, detail; @override Widget build(BuildContext c) => Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, style: Theme.of(c).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w800)), Text(detail, style: const TextStyle(color: Color(0xFF667085)))]); }
class ActionTile extends StatelessWidget { const ActionTile(this.icon, this.label, this.color, {super.key}); final IconData icon; final String label; final Color color; @override Widget build(BuildContext c) => InkWell(onTap: () {}, borderRadius: BorderRadius.circular(15), child: Ink(width: 175, padding: const EdgeInsets.all(15), decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(15), border: Border.all(color: const Color(0xFFE7ECF3))), child: Row(mainAxisSize: MainAxisSize.min, children: [Icon(icon, color: color), const SizedBox(width: 10), Text(label, style: const TextStyle(fontWeight: FontWeight.w700))]))); }
class Alerts extends StatelessWidget { const Alerts({super.key}); @override Widget build(BuildContext c) => Card(elevation: 0, color: Colors.white, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20), side: const BorderSide(color: Color(0xFFE7ECF3))), child: const Column(children: [Alert('Premium Coffee Beans', 'SKU-00132', '6 units left', Color(0xFFD97706)), Divider(height: 1), Alert('Packaging Boxes - Medium', 'SKU-00598', '11 units left', Color(0xFFD97706)), Divider(height: 1), Alert('Vanilla Syrup', 'SKU-00324', 'Out of stock', Color(0xFFDC2626))])); }
class Alert extends StatelessWidget { const Alert(this.item, this.sku, this.status, this.color, {super.key}); final String item, sku, status; final Color color; @override Widget build(BuildContext c) => ListTile(contentPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 6), leading: Container(width: 42, height: 42, decoration: BoxDecoration(color: color.withValues(alpha: .1), borderRadius: BorderRadius.circular(12)), child: Icon(Icons.inventory_2_outlined, color: color)), title: Text(item, style: const TextStyle(fontWeight: FontWeight.w700)), subtitle: Text(sku), trailing: Text(status, style: TextStyle(color: color, fontWeight: FontWeight.w700))); }
class ChartCard extends StatelessWidget { const ChartCard({super.key}); @override Widget build(BuildContext c) => Card(elevation: 0, color: Colors.white, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20), side: const BorderSide(color: Color(0xFFE7ECF3))), child: const Padding(padding: EdgeInsets.all(24), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Stock movement', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w800)), SizedBox(height: 5), Text('Incoming and outgoing stock over the last 6 months', style: TextStyle(color: Color(0xFF667085))), SizedBox(height: 30), Icon(Icons.show_chart_rounded, color: mint, size: 80), SizedBox(height: 15), Text('Detailed reporting will appear here as inventory data is connected.', style: TextStyle(color: Color(0xFF667085)))]))); }
